{% set name = "mxtools" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mxtools-{{ version }}.tar.gz
  sha256: 19719de12d9bda87bc665c3586cc509d8e4190af41ea2bf4ac26794288190e80

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bluesky
    - ophyd
    - pyepics

test:
  imports:
    - mxtools
    - mxtools.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NSLS-II-AMX/mxtools
  summary: Common code for the MX beamlines at NSLS-II (AMX, FMX).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JunAishima
    - mrakitin
