{% set name = "mxtools" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mxtools-{{ version }}.tar.gz
  sha256: 610c47b0abde55e92be174b52788c4df8d69ffe0b61d8d6b64ed423bda62ae13

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bluesky
    - ophyd
    - pyepics
    - tiled
    # TODO: remove tiled once databroker has tiled as a dependency for
    # databroker > 2.0.0b4

test:
  imports:
    - mxtools
    - mxtools.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NSLS-II-AMX/mxtools
  summary: Common code for the MX beamlines at NSLS-II (AMX, FMX).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JunAishima
    - mrakitin
