{% set name = "mxtools" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mxtools-{{ version }}.tar.gz
  sha256: 298ec2a47187af579a86633a4d25ad4a64904b229c27914ed47ea778f61b8bb0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bluesky
    - ophyd
    - pyepics
    - tiled
    # TODO: remove tiled once databroker has tiled as a dependency for
    # databroker > 2.0.0b4

test:
  imports:
    - mxtools
    - mxtools.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NSLS-II-AMX/mxtools
  summary: Common code for the MX beamlines at NSLS-II (AMX, FMX).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JunAishima
    - mrakitin
